version: '3'

services:
  app:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 app_subscription.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: new_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

