# Generated by Django 5.0 on 2023-12-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
